### PR TITLE
improve program size

### PR DESCRIPTION
**Pull request by FonseAntoIM**
setAll function
* change input type so we can edit valve
* add additional error test, so value could be only 0/1 
* reduce if statement

set function:
* add additional error test, value could be only 0/1
* replace if statemen by ? operator

### CODE REVIEW

**Comment by RobTillaart** [comment]
Thanks, will look at it later today

**Comment by RobTillaart** [comment]
Mmm. 
Seems i need to fix build too

**Comment by RobTillaart** [comment]
I changed the code of the library locally for the UNO and ran example **boolArrayDemo0.ino**

No change in program size:

```
Sketch uses 4364 bytes (13%) of program storage space. Maximum is 32256 bytes.
Global variables use 406 bytes (19%) of dynamic memory, leaving 1642 bytes for local variables. Maximum is 2048 bytes.
```

Execution for setting to 1 was faster but setting to 0 was slower by approx same amount (SET TEST0)
(I need to redo the test sketch as it is not 100% correct in its messages and naming and test 3 is not OK either )

----

ran example **boolArrayDemo2.ino**

```
Sketch uses 4524 bytes (14%) of program storage space. Maximum is 32256 bytes.
Global variables use 440 bytes (21%) of dynamic memory, leaving 1608 bytes for local variables. Maximum is 2048 bytes.
```

The original 0.2.3
```
Sketch uses 4534 bytes (14%) of program storage space. Maximum is 32256 bytes.
```
So indeed a gain of 10 bytes.

performance of **clear** got worse   42  -> 50 millis  (+20%)
performance of **setAll** improved minimal


PROPOSED VERSION
```
BOOLARRAY_LIB_VERSION:	0.2.3
Bool array size:	1000

get
DURATION:	5648
DURATION:	9964
       X:	0

set
DURATION:	4176
DURATION:	7568

clear
DURATION:	50192
DURATION:	99940

setAll
DURATION:	50208
DURATION:	99840

toggle
DURATION:	3984
DURATION:	7320
Done...
```

The original 0.2.3 
```
BOOLARRAY_LIB_VERSION:	0.2.3
Bool array size:	1000

get
DURATION:	5648
DURATION:	9964
       X:	0

set
DURATION:	4176
DURATION:	7568

clear
DURATION:	42396
DURATION:	84352

setAll
DURATION:	50332
DURATION:	100100

toggle
DURATION:	3996
DURATION:	7320
Done...
```

As **clear** is degraded so much I will not merge the PR for now. However I will investigate if I can find the cause.
My hypothesis is that the use of the value variable is slower than assigning a constant 0. 

to be continued.

**Comment by RobTillaart** [comment]
Created a branch develop to
- fix the build process
- look at your proposal for **setAll()**    (saves 10 bytes and potentially faster?)


your proposal for **set()** just swapped performance of setting to zero and setting to 1 and no gain in size

**Comment by RobTillaart** [comment]
Found a bug in your proposal of **setAll()**  
0 is defined as **false** and all other values are defined as **true**.
So multiplying  ``` value *= 0xFF``` could give pretty weird results.

**Comment by RobTillaart** [comment]
check - https://github.com/RobTillaart/BoolArray/pull/8

ran example **boolArrayDemo2.ino**

```
Sketch uses 4510 bytes (13%) of program storage space. Maximum is 32256 bytes.
Global variables use 441 bytes (21%) of dynamic memory, leaving 1607 bytes for local variables. Maximum is 2048 bytes.
```
Compared to figures of 0.2.3
1 byte RAM more    (uint8_t _bytes)
24 bytes PROGMEM less   (due to _bytes)

performance improved a bit over 0.2.3 for **clear()** and **setAll()**
```
BOOLARRAY_LIB_VERSION:	0.2.4
Bool array size:	1000

get
DURATION:	5652
DURATION:	9964
       X:	0

set
DURATION:	4176
DURATION:	7572

clear
DURATION:	41200
DURATION:	81960

setAll
DURATION:	49136
DURATION:	97712

toggle
DURATION:	3996
DURATION:	7320
Done...
```

----

Also cleaned up **boolArrayDemo0.ino** so output is more meaningful (a bit)

Added build badges to the readme.md file to see status.

---- 

I tried your optimizations again (on UNO) but they gave same or worse results so these are not included.
Nevertheless you inspired to look at the performance / size of the code again resulting in the improvements.

**Comment by FonseAntoIM** [comment]
I should have tried your performance tests. The results and the analysis have been very interesting.
thanks for the support

**Pull request closed without merging**
